#include"Header.h"

int main()
{
	int size = 0;
	unsigned long long cp = 0;
	unsigned long long time = 0;
	int* selectionsort_arr;
	int* insertionsort_arr;
	int* bubblesort_arr;
	int* heapsort_arr;
	int* mergesort_arr;
	int* quicksort_arr;
	int* radixsort_arr;
	int* shakersort_arr;
	int* shellsort_arr;
	int* countingsort_arr;
	int* flashsort_arr;
	int* arr;
	copyAndGenerateData(arr, size, 2, 0, selectionsort_arr, insertionsort_arr, bubblesort_arr, heapsort_arr, mergesort_arr, quicksort_arr, radixsort_arr, shakersort_arr, shellsort_arr, countingsort_arr, flashsort_arr);
	radixSort(flashsort_arr, size, time, cp);
	radixSort(arr, size, time, cp);
	// Display output
	cout << ">Comparision and time using<" << endl;
	cout << "============================" << endl;
	cout << "Selection sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Insertion sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Bubble sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Heap sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Merge sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Quick sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Radix sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Shaker sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Shell sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Counting sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	cout << "Flash sort" << endl;
	cout << "Comparision: " << cp << endl;
	cout << "Time using (micro second): " << time << endl;
	cout << "============================" << endl;
	deleteData(selectionsort_arr);
	deleteData(insertionsort_arr);
	deleteData(bubblesort_arr);
	deleteData(heapsort_arr);
	deleteData(mergesort_arr);
	deleteData(quicksort_arr);
	deleteData(radixsort_arr);
	deleteData(shakersort_arr);
	deleteData(shellsort_arr);
	deleteData(countingsort_arr);
	deleteData(flashsort_arr);
	deleteData(arr);
}